export const NEXT_STEP = 'STEP/NEXT_STEP'

export const UPLOAD_FILE = 'FILE/UPLOAD_FILE'
export const GET_METADATA = 'FILE/GET_METADATA'
export const SET_SCANNER_STATUS = 'FILE/SET_SCANNER_STATUS'

export const ACTIVATE_PROCESS = 'CONVERTER/ACTIVATE_PROCESS'
export const PROGRESS_PERCENT = 'CONVERTER/PROGRESS_PERCENT'
export const ADD_CONVERTING_FILE = 'CONVERTER/ADD_CONVERTING_FILE'
export const CONVERTATION_KILL = 'CONVERTER/CONVERTATION_KILL'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
