export const NEXT_STEP = 'STEP/NEXT_STEP'

export const UPLOAD_FILE = 'FILE/UPLOAD_FILE'
export const GET_METADATA = 'FILE/GET_METADATA'

export const ACTIVATE_PROCESS = 'CONVERTER/ACTIVATE_PROCESS'
export const PROGRESS_PERCENT = 'CONVERTER/PROGRESS_PERCENT'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
